BROADCAST_PORT = 5005
DISCOVERY_MESSAGE = "DISCOVER_AUCTION_LEADER"
PEER_DISCOVERY_PREFIX = "PEER_DISCOVERY"
PEER_RESPONSE_PREFIX = "PEER_RESPONSE"
LEADER_FOUND_PREFIX = "LEADER_FOUND"
LEADER_IP_PREFIX = "LEADER_IP"

# Election Messages
HS_PROBE_PREFIX = "HS_PROBE" # Format: HS_PROBE:SENDER:TARGET:ORIGIN:PHASE:HOPS:MAX:DIR:PEER_HASH
HS_REPLY_PREFIX = "HS_REPLY" # Format: HS_REPLY:SENDER:TARGET:ORIGIN:PHASE:DIR
ELECTION_RESTART_PREFIX = "ELECTION_RESTART"
