BROADCAST_PORT = 5005
DISCOVERY_MESSAGE = "DISCOVER_AUCTION_LEADER"
PEER_DISCOVERY_PREFIX = "PEER_DISCOVERY"
PEER_RESPONSE_PREFIX = "PEER_RESPONSE"
LEADER_FOUND_PREFIX = "LEADER_FOUND"
LEADER_IP_PREFIX = "LEADER_IP"

# Election Messages
HS_PROBE_PREFIX = "HS_PROBE" # Format: HS_PROBE:SENDER:TARGET:ORIGIN:PHASE:HOPS:MAX:DIR:PEER_HASH
HS_REPLY_PREFIX = "HS_REPLY" # Format: HS_REPLY:SENDER:TARGET:ORIGIN:PHASE:DIR
ELECTION_RESTART_PREFIX = "ELECTION_RESTART"

GET_AUCTIONS_MESSAGE = "GET_AUCTIONS"
CREATE_AUCTION_MESSAGE = "CREATE_AUCTION"

# Worker TCP messages
WORKER_TCP_PORT = 0
WORKER_CREATE_MESSAGE = "WORKER_CREATE"
WORKER_JOIN_MESSAGE = "WORKER_JOIN"
WORKER_BID_MESSAGE = "WORKER_BID"
WORKER_BID_UPDATE_MESSAGE = "WORKER_BID_UPDATE"
WORKER_STATUS_MESSAGE = "WORKER_STATUS"
WORKER_RESULT_MESSAGE = "WORKER_RESULT"
